### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Klausmd5** [SapuSeven/BetterUntis#123]
<details>
<summary>Logs</summary>

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:506)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	... 1 more
Caused by: java.lang.NoSuchMethodException: d.a.a.m.a.<init> [class d.a.a.g.b.b$b, class d.a.a.g.c.j, class d.a.a.a.a.a]
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getConstructor(Class.java:1728)
	at d.a.a.m.a$b.a(Unknown Source:23)
	at o.n.v.getValue(:4)
	at d.a.a.i.b.x0(Unknown Source:2)
	at d.a.a.i.b.P(Unknown Source:11)
	at androidx.fragment.app.Fragment.g0(Unknown Source:15)
	at o.l.d.r.U(:29)
	at o.l.d.r.S(:1)
	at o.l.d.r.T(Unknown Source:47)
	at o.l.d.a.l(:2)
	at o.l.d.r.D(:7)
	at o.l.d.r.Z(Unknown Source:84)
	at o.l.d.r.B(:4)
	at o.l.d.r$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8154)
	... 3 more

```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.0 (24)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Thanks for the report.
See #121 for updates.
