### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#131]
<details>
<summary>Logs</summary>

```
l.b.x.e: Unexpected JSON token at offset 246: Expected '{, kind: a'.
 JSON input: .....ces":null,"text":null,"topic":null,"homeWorks":[{"id":1610,".....
	at i.a.a.a.u0.m.l1.a.e(Unknown Source:29)
	at l.b.x.u.e.c(Unknown Source:7)
	at l.b.x.u.j.b(:4)
	at com.sapuseven.untis.models.untis.UntisTopic$$serializer.deserialize(Unknown Source:12)
	at com.sapuseven.untis.models.untis.UntisTopic$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.u0.m.l1.a.C(:12)
	at l.b.x.u.j.s(Unknown Source:5)
	at l.b.u.a.h(Unknown Source:10)
	at com.sapuseven.untis.models.untis.response.UntisPeriodData$$serializer.deserialize(Unknown Source:420)
	at com.sapuseven.untis.models.untis.response.UntisPeriodData$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.u0.m.l1.a.C(:12)
	at l.b.x.u.j.s(Unknown Source:5)
	at l.b.u.a.h(Unknown Source:10)
	at l.b.w.n0.j(Unknown Source:118)
	at l.b.w.n0.g(Unknown Source:2)
	at l.b.w.a.patch(:3)
	at l.b.w.a.deserialize(Unknown Source:13)
	at i.a.a.a.u0.m.l1.a.C(:12)
	at l.b.x.u.j.s(Unknown Source:5)
	at l.b.u.a.h(Unknown Source:10)
	at com.sapuseven.untis.models.untis.response.PeriodDataResult$$serializer.deserialize(Unknown Source:85)
	at com.sapuseven.untis.models.untis.response.PeriodDataResult$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.u0.m.l1.a.C(:12)
	at l.b.x.u.j.s(Unknown Source:5)
	at i.a.a.a.u0.m.l1.a.B(Unknown Source:11)
	at l.b.x.u.j.x(:1)
	at l.b.u.a.g(Unknown Source:10)
	at com.sapuseven.untis.models.untis.response.PeriodDataResponse$$serializer.deserialize(Unknown Source:101)
	at com.sapuseven.untis.models.untis.response.PeriodDataResponse$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.u0.m.l1.a.C(:12)
	at l.b.x.u.j.s(Unknown Source:5)
	at l.b.x.a.a(:1)
	at com.sapuseven.untis.viewmodels.PeriodDataViewModel.loadPeriodData(:17)
	at com.sapuseven.untis.viewmodels.PeriodDataViewModel$h.d(Unknown Source:11)
	at i.w.k.a.a.j(:2)
	at l.a.i0.run(:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.2 (26)_
- Installation source: _com.android.vending_

**Comment by Domi04151309** [comment]
Is it intentional that the dialog is displayed as activity?

**Comment by SapuSeven** [comment]
Yes, the dialog is now a Fragment. This made it easier to implement `LiveData` and teacher specific features like absence checking. I found that the contents of the dialog became too complex for a simple dialog.

As for the crash: Yet another simple fix, but hard to avoid if you don't really know the Untis API.

**Comment by SapuSeven** [comment]
Please try the new [build#600](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=600) and check if the issue is finally resolved.

**Comment by Domi04151309** [comment]
It works

**Comment by SapuSeven** [comment]
Great, I'll publish a release shortly
