### ISSUE TITLE
App crashes by clicking on info center

### ISSUE THREAD

**Issue by SimonIT** [SapuSeven/BetterUntis#14]
The app crashes by clicking on info center with this stacktrace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sapuseven.untis.debug, PID: 9920
    kotlinx.serialization.json.JsonUnknownKeyException: Strict JSON encountered unknown key: jsonrpc
    You can disable strict mode to skip unknown keys
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeElementIndex(StreamingJsonInput.kt:96)
        at com.sapuseven.untis.models.untis.response.ExamResponse$$serializer.deserialize(Unknown Source:18)
        at com.sapuseven.untis.models.untis.response.ExamResponse$$serializer.deserialize(ExamResponse.kt:7)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
        at kotlinx.serialization.CoreKt.decode(Core.kt:79)
        at kotlinx.serialization.json.Json.parse(Json.kt:148)
        at com.sapuseven.untis.activities.InfoCenterActivity.loadExams(InfoCenterActivity.kt:217)
        at com.sapuseven.untis.activities.InfoCenterActivity$loadExams$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by SapuSeven** [comment]
Did you compile the app yourself or did you use the builds from my website?

**Comment by SimonIT** [comment]
I compiled it myself

**Comment by SapuSeven** [comment]
In that case you first have to clean the project (Android Studio: Build -> Clean Project). For some reason Kotlin Serialization sometimes doesn't compile serializable classes with superclasses correctly if they are edited.

**Comment by SimonIT** [comment]
That was easy, thanks. I got no experience with kotlin
