### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by rauferd** [SapuSeven/BetterUntis#160]
<details>
<summary>Logs</summary>

```
Please attach the compressed log files to this issue.
They have been saved to `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1607177100841.zip`
```
</details>

**Additional information**

- Android version: _7.1.2_
- BetterUntis version: _3.4.3 (27)_
- Installation source: _com.android.packageinstaller_

**Comment by rauferd** [comment]
This is the latest version from F-Droid.

This crash happened three times in the past week, so I decided to report it.

After restarting the app, everything works just fine. No way to reproduce the crash on purpose.

**Comment by SapuSeven** [comment]
Can you upload the log files as described in the issue text?

**Comment by rauferd** [comment]
I apologize. I seem to be unable to upload the .zip-file for technical reasons.
Please find below the content of the two logfiles "_1607177093025.log" and "_1607177093012.log" (exactly the same content):
```
java.lang.NullPointerException: Attempt to read from field 'float android.content.res.Configuration.fontScale' on a null object reference
	at android.content.res.Configuration.setTo(Configuration.java:752)
	at android.content.res.Configuration.<init>(Configuration.java:739)
	at android.app.ActivityThread.createNewConfigAndUpdateIfNotNull(ActivityThread.java:4666)
	at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4736)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:4650)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3566)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by SapuSeven** [comment]
No worries.

I did a little research and found the following StackOverflow thread: [Crash when resuming Activity due to NPE](https://stackoverflow.com/questions/57026240/crash-when-resuming-activity-due-to-npe)

Apparently this is a bug of the DayNight theme in Android 7.
I'm not sure how I can solve this yet.

**Comment by SapuSeven** [comment]
The upcoming Material 3 update won't be using the DayNight theme any more, so this should be resolved with the next release. Feel free to re-open if the issue persists.
