### ISSUE TITLE
App crash while loading timetable

### ISSUE THREAD

**Issue by Perflyst** [SapuSeven/BetterUntis#2]
The app crashes while loading the timetable with internet connection.
If there is no internet connection I get an error like "mobile.webuntis.com" not found. Why does it even connect to mobile.webuntis.com?

BetterUntis is built from latest develop branch commit.

```
09-21 08:44:40.685  6971  6971 D TimetableLoaderDebug: target TimetableLoaderTarget(startDate=2019-09-21, endDate=2019-09-21, id=9213, type=STUDENT) (requestId 0): network request success, returning
09-21 08:44:40.687  6971  6971 D TimetableLoaderDebug: target TimetableLoaderTarget(startDate=2019-09-21, endDate=2019-09-21, id=9213, type=STUDENT) (requestId 0): saving to cache: STUDENT-9213-2019-09-21-2019-09-21
09-21 08:44:40.766  6971  6971 D TimetableLoaderDebug: target TimetableLoaderTarget(startDate=2019-09-15, endDate=2019-09-21, id=9213, type=STUDENT) (requestId 0): network request success, returning
09-21 08:44:40.793  6971  6971 D MainActivityDebug: addData received 21 items from 2019-09-15 until 2019-09-21
09-21 08:44:40.793  6971  6985 I art     : Do full code cache collection, code=108KB, data=122KB
09-21 08:44:40.794  6971  6985 I art     : Starting a blocking GC JitCodeCache
09-21 08:44:40.794  6971  6985 I art     : After code cache collection, code=80KB, data=62KB
09-21 08:44:40.824  6971  6971 E AndroidRuntime: FATAL EXCEPTION: main
09-21 08:44:40.824  6971  6971 E AndroidRuntime: Process: com.sapuseven.untis.debug, PID: 6971
09-21 08:44:40.824  6971  6971 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=10; index=10
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at com.sapuseven.untis.activities.MainActivity.mergeItems(MainActivity.kt:461)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at com.sapuseven.untis.activities.MainActivity.prepareItems(MainActivity.kt:426)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at com.sapuseven.untis.activities.MainActivity.addData(MainActivity.kt:687)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at com.sapuseven.untis.helpers.timetable.TimetableLoader.loadFromServer(TimetableLoader.kt:98)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at com.sapuseven.untis.helpers.timetable.TimetableLoader$loadFromServer$1.invokeSuspend(TimetableLoader.kt)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-21 08:44:40.824  6971  6971 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-21 08:44:40.828  5066  5256 W ActivityManager:   Force finishing activity com.sapuseven.untis.debug/com.sapuseven.untis.activities.MainActivity
09-21 08:44:40.835  5066  7031 W DropBoxManagerService: Dropping: data_app_crash (1277 > 0 bytes)
```

**Comment by SapuSeven** [comment]
Thanks for reporting!
I recently updated the code for merging multi-hour lessons, it looks like I missed something. I'll fix it in a day or two.

Regarding the URL:
I noticed the original Untis app is using the following URL for every school and server: "https://mobile.webuntis.com/ms/app/[SCHOOL-ID]". It looked like a better way to send requests, so I implemented that as well.

**Comment by Perflyst** [comment]
Thanks for the explanation, I need to add mobile.webuntis.com to my proxy service.

**Comment by SapuSeven** [comment]
I fixed the issue, can you try the app with the new commit to verify?

**Comment by Perflyst** [comment]
Everything is working now as expected.
