### ISSUE TITLE
[Crash Report] App crashes on startup

### ISSUE THREAD

**Issue by konstantinhirschfeld** [SapuSeven/BetterUntis#201]
APP crashes immediately after beging opened, shows this error message:

<details>
<summary>Logs</summary>

```
l.b.e: Field 'message' is required, but it was missing
	at com.sapuseven.untis.models.untis.UntisError.<init>(Unknown Source:30)
	at com.sapuseven.untis.models.untis.UntisError$$serializer.deserialize(Unknown Source:126)
	at com.sapuseven.untis.models.untis.UntisError$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.u0.m.l1.a.C(:12)
	at l.b.x.u.j.s(Unknown Source:5)
	at i.a.a.a.u0.m.l1.a.B(Unknown Source:11)
	at l.b.x.u.j.x(:1)
	at l.b.u.a.g(Unknown Source:10)
	at com.sapuseven.untis.models.untis.response.MessageResponse$$serializer.deserialize(Unknown Source:147)
	at com.sapuseven.untis.models.untis.response.MessageResponse$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.u0.m.l1.a.C(:12)
	at l.b.x.u.j.s(Unknown Source:5)
	at l.b.x.a.a(:1)
	at com.sapuseven.untis.activities.MainActivity.W(:15)
	at com.sapuseven.untis.activities.MainActivity$e.d(Unknown Source:12)
	at i.w.k.a.a.j(:2)
	at l.a.i0.run(:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

**Additional information**

- Android version: _11_
- BetterUntis version: _3.4.5 (29)_
- Installation source: _org.fdroid.fdroid.privileged_

**Comment by SapuSeven** [comment]
Due to the high number of crashes lately (about 50 reports in the last hour), I assume this is caused by Untis changing their API again.

**Comment by konstantinhirschfeld** [comment]
Ah, that makes sence.

**Comment by SapuSeven** [comment]
I'll keep this issue open to keep track of progress because resolving this needs an app update.

**Comment by DreamyLynn** [comment]
This will require a big rework. They changed the authentication system ground-up.

**Comment by SapuSeven** [comment]
Please take a look at [build#737](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=737).
I updated the login process and successfully tested anonymous login.
Clean all app data if necessary and log in as usual. Please report back if you can login and access the timetable screen without crashing. (There may be an error regarding invalid JSON when trying to view the timetable, this will be fixed later.)

**Comment by lm41** [comment]
Yes, the login works. The timetable doesnt load. And it gets an error.

**Comment by eliasbnr** [comment]
I don't really know if this is only for debug build but I'm getting this error after logging in using Android 12:

<details>
<summary>Logs</summary>

```
java.lang.RuntimeException: Unable to start receiver com.sapuseven.untis.receivers.StartupReceiver: java.lang.IllegalArgumentException: com.sapuseven.untis.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4317)
	at android.app.ActivityThread.access$1600(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalArgumentException: com.sapuseven.untis.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
	at com.sapuseven.untis.receivers.StartupReceiver.onReceive(StartupReceiver.kt:36)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4308)
	... 9 more

```
</details>

**Additional information**

- Android version: _12_
- BetterUntis version: _3.4.5-DEBUG (31)_
- Installation source: _com.google.android.packageinstaller_

**Comment by KaratekHD** [comment]
In this build, logging in with a QR code does not work, as seen in the screenshot. It does work however if I replace the school name with the ID.

![Screenshot_20211207-075105_BetaUntis__01.png](https://user-images.githubusercontent.com/38097062/144980732-36ffdf4b-b21c-4d1e-9e35-409237505bba.png)

I'm not sure if this is a general problem or something with the debug build.

**Comment by bennetrr** [comment]
I get the same error as @KaratekHD

**Comment by SapuSeven** [comment]
Thanks for the feedback, I'll have another build ready later today that addresses the new issues.

**Comment by SapuSeven** [comment]
Alright, I just pushed some fixes. Please test [build#747](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=747), if everything works I'll publish a Google Play Release.

**Comment by eliasbnr** [comment]
> Alright, I just pushed some fixes. Please test [build#747](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=747), if everything works I'll publish a Google Play Release.

It's working fine for me.

**Comment by konstantinhirschfeld** [comment]
> Alright, I just pushed some fixes. Please test [build#747](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=747), if everything works I'll publish a Google Play Release.

Are you going to update the fdroid Version as well?

**Comment by bennetrr** [comment]
It works for me when I enter the School Number, but entering the School Name (which is given by the QR-Code in my case) just gives me an error: "Ungültige Schul-ID!"

**Comment by Luis-L-B** [comment]
> Alright, I just pushed some fixes. Please test [build#747](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=747), if everything works I'll publish a Google Play Release.

Its mostly working. Login and showing lessons works, however certain objects like "exam" are not processed. (Unknown JSON object "exam" encountered, value: {"id":0000,"examtype":"*Type of exam*","name": "*custom name*", "*Custom Text*"}
There are also other Objects like StaffAttachments or staffInfo, but we dont use those

**Comment by SapuSeven** [comment]
@nonamewastaken:
> Are you going to update the fdroid Version as well?

Yes, FDroid and Play Store updates are linked and will update simultaneously.

@bennetrr:
> It works for me when I enter the School Number, but entering the School Name (which is given by the QR-Code in my case) just gives me an error: "Ungültige Schul-ID!"

Could you provide me with the exact values for the school name and the school number to check this out? You can email me directly.

@Luis-L-B:
> Its mostly working. Login and showing lessons works, however certain objects like "exam" are not processed. (Unknown JSON object "exam" encountered, value: `{"id":0000,"examtype":"_Type of exam_","name": "_custom name_", "_Custom Text_"}` There are also other Objects like `StaffAttachments` or `staffInfo`, but we dont use those

These objects are not used by BetterUntis (yet), so you can ignore these errors.

**Comment by lm41** [comment]
It works well.

**Comment by KaratekHD** [comment]
> Alright, I just pushed some fixes. Please test [build#747](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=747), if everything works I'll publish a Google Play Release.

Worked just fine for me, I had to clear app data for it to work though.

**Comment by SapuSeven** [comment]
The update has just been released 🎉
It will be available to Google Play Beta and FDroid users soon.

**Comment by konstantinhirschfeld** [comment]
Awesome, tysm

**Comment by ChuaatDev** [comment]
Would it be possible for you to update the wiki on how to authenticate the user now?

**Comment by nautilusx** [comment]
3.47 works fine! @SapuSeven THANK YOU!
