### ISSUE TITLE
[Bug Report] App Crash in Startup (Field 'message' required)

### ISSUE THREAD

**Issue by rauferd** [SapuSeven/BetterUntis#215]
The app crashes immediately after startup. Every couple of starts, it does make it to the "Errors" screen, luckily, but crashes immediately when I switch to the timetable or any other view.
I have been using the app (F-Droid build) for more than two years before without issues.

I have no idea how to debug or fix this, but I can carry out instructions to help investigate/fix this problem.

<details>
<summary>Logs</summary>

```
l.b.e: Field 'message' is required, but it was missing
	at com.sapuseven.untis.models.untis.UntisError.<init>(Unknown Source:30)
	at com.sapuseven.untis.models.untis.UntisError$$serializer.deserialize(Unknown Source:126)
	at com.sapuseven.untis.models.untis.UntisError$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.u0.m.l1.a.C(:12)
	at l.b.x.u.j.s(Unknown Source:5)
	at i.a.a.a.u0.m.l1.a.B(Unknown Source:11)
	at l.b.x.u.j.x(:1)
	at l.b.u.a.g(Unknown Source:10)
	at com.sapuseven.untis.models.untis.response.MessageResponse$$serializer.deserialize(Unknown Source:147)
	at com.sapuseven.untis.models.untis.response.MessageResponse$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.u0.m.l1.a.C(:12)
	at l.b.x.u.j.s(Unknown Source:5)
	at l.b.x.a.a(:1)
	at com.sapuseven.untis.activities.MainActivity.W(:15)
	at com.sapuseven.untis.activities.MainActivity$e.d(Unknown Source:12)
	at i.w.k.a.a.j(:2)
	at l.a.i0.run(:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.5 (29)_
- Installation source: _com.android.packageinstaller_

**Comment by SapuSeven** [comment]
Thanks for reporting. This is being tracked in #201.
