### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by johahauf** [SapuSeven/BetterUntis#230]
<details>
<summary>Logs</summary>

```
v7.h: Unexpected JSON token at offset 358: Unexpected 'null' value instead of string literal
JSON input: .....tgart","mobileServiceUrl":null},{"server":"achilles.webuntis.....
	at u7.j.d(Unknown Source:35)
	at u7.j.e(Unknown Source:34)
	at v7.a.o(Unknown Source:9)
	at v7.a.p(Unknown Source:6)
	at v7.a.m(:2)
	at v7.s.A(:2)
	at s7.a.p(Unknown Source:5)
	at com.sapuseven.untis.models.UntisSchoolInfo$$serializer.deserialize(Unknown Source:118)
	at com.sapuseven.untis.models.UntisSchoolInfo$$serializer.deserialize(Unknown Source:0)
	at u7.j.i(:11)
	at v7.s.i(Unknown Source:5)
	at s7.a.o(:1)
	at s7.c$a.a(Unknown Source:1)
	at t7.e0.h(Unknown Source:17)
	at t7.a.f(:3)
	at t7.a.deserialize(Unknown Source:6)
	at u7.j.i(:11)
	at v7.s.i(Unknown Source:5)
	at s7.a.o(:1)
	at com.sapuseven.untis.models.untis.response.SchoolSearchResult$$serializer.deserialize(Unknown Source:63)
	at com.sapuseven.untis.models.untis.response.SchoolSearchResult$$serializer.deserialize(Unknown Source:0)
	at u7.j.i(:11)
	at v7.s.i(Unknown Source:5)
	at s7.a.E(:1)
	at com.sapuseven.untis.models.untis.response.SchoolSearchResponse$$serializer.deserialize(Unknown Source:75)
	at com.sapuseven.untis.models.untis.response.SchoolSearchResponse$$serializer.deserialize(Unknown Source:0)
	at u7.j.i(:11)
	at v7.s.i(Unknown Source:5)
	at u7.a.b(Unknown Source:21)
	at m3.r.e(:27)
	at r4.a.l(:4)
	at k7.f0.run(:2)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.7 (31)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
That's odd.
I'm pretty sure 4877f12b62d284af6b5243326d6f4efceed61aa6 fixed this.
Could you try the latest debug build from sapuseven.com?

**Comment by johahauf** [comment]
I reinstalled the app and now it is working so this can be closed
