### ISSUE TITLE
[Bug Report] and [Crash Report]

### ISSUE THREAD

**Issue by cookiegruemel** [SapuSeven/BetterUntis#385]
![Screenshot_20230517_103214_BetterUntis](https://github.com/SapuSeven/BetterUntis/assets/75181498/6f65d798-b60c-454b-be4b-a08c62f07553)
![Screenshot_20230517_103200_BetterUntis](https://github.com/SapuSeven/BetterUntis/assets/75181498/806b2729-4d75-4479-93ef-2a2a83f9f1fb)
<details>
<summary>Logs</summary>

```
java.lang.IllegalArgumentException: com.sapuseven.untis: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:688)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:675)
	at com.sapuseven.untis.receivers.AutoMuteSetup.b(:21)
	at d4.b.w(Unknown Source:14)
	at y3.b$c.e(:22)
	at q4.a.j(:4)
	at j7.f0.run(:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>

**Additional information**

- Android version: _13_
- BetterUntis version: _3.5.1 (34)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
This has been fixed already (see #369). Please wait for the next release or use the Beta version from the Play Store.
