### ISSUE TITLE
[Bug Report] Crash after opening

### ISSUE THREAD

**Issue by s3n-w6i** [SapuSeven/BetterUntis#40]
**Description**
APP crashes immediatly after opening it. Works in both OpenUntis and Untis Mobile.

**Actual behavior**
Open app, timetable and user information loading in background, BetterUntis shows Dialog with crash report, Android shows "APP crashed"-popup

**Expected behavior**
Don't crash

<details>
  <summary><b>Logs</b></summary>

  ```
j.c.d0.s: Invalid JSON at 49831: Expected string or non-null literal
	at j.c.d0.w.e.c(Unknown Source:14)
	at j.c.d0.w.k.n(Unknown Source:2)
	at j.c.h.b(Unknown Source:2)
	at com.sapuseven.untis.models.untis.timetable.PeriodExam$$serializer.deserialize(Unknown Source:61)
	at com.sapuseven.untis.models.untis.timetable.PeriodExam$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.t0.m.z0.a(:64)
	at j.c.d0.w.k.a(Unknown Source:2)
	at i.a.a.a.t0.m.z0.b(Unknown Source:8)
	at j.c.d0.w.k.b(:6)
	at j.c.h.a(Unknown Source:5)
	at com.sapuseven.untis.models.untis.timetable.Period$$serializer.deserialize(Unknown Source:405)
	at com.sapuseven.untis.models.untis.timetable.Period$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.t0.m.z0.a(:64)
	at j.c.d0.w.k.a(Unknown Source:2)
	at j.c.h.b(Unknown Source:5)
	at j.c.c0.a0.a(Unknown Source:8)
	at j.c.c0.a.patch(:3)
	at j.c.c0.a.deserialize(Unknown Source:10)
	at i.a.a.a.t0.m.z0.a(:64)
	at j.c.d0.w.k.a(Unknown Source:2)
	at j.c.h.b(Unknown Source:5)
	at com.sapuseven.untis.models.untis.UntisTimetable$$serializer.deserialize(Unknown Source:74)
	at com.sapuseven.untis.models.untis.UntisTimetable$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.t0.m.z0.a(:64)
	at j.c.d0.w.k.a(Unknown Source:2)
	at j.c.h.b(Unknown Source:5)
	at com.sapuseven.untis.models.untis.response.TimetableResult$$serializer.deserialize(Unknown Source:50)
	at com.sapuseven.untis.models.untis.response.TimetableResult$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.t0.m.z0.a(:64)
	at j.c.d0.w.k.a(Unknown Source:2)
	at i.a.a.a.t0.m.z0.b(Unknown Source:8)
	at j.c.d0.w.k.b(:6)
	at j.c.h.a(Unknown Source:5)
	at com.sapuseven.untis.models.untis.response.TimetableResponse$$serializer.deserialize(Unknown Source:127)
	at com.sapuseven.untis.models.untis.response.TimetableResponse$$serializer.deserialize(Unknown Source:0)
	at i.a.a.a.t0.m.z0.a(:64)
	at j.c.d0.w.k.a(Unknown Source:2)
	at i.a.a.a.t0.m.z0.a(Unknown Source:5)
	at j.c.d0.a.a(Unknown Source:17)
	at d.a.a.a.a.c.a(:38)
	at d.a.a.a.a.c$d.b(Unknown Source:13)
	at i.w.j.a.a.a(Unknown Source:9)
	at j.a.a0.run(:11)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6746)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
</details>

**Additional information (please replace)**
 - Android 9
 - BetterUntis version: Latest at the time oft writing from F-Droid

**Comment by s3n-w6i** [comment]
Seems from the logs like it's due to some exam. There is no exam in this week, but there was one in the week before (which makes sense given that it displays the current week).

**Comment by s3n-w6i** [comment]
When opening the app when offline, the error does not occurand the current week is shown, proving that it has something to do with the exam in the week before

**Comment by SapuSeven** [comment]
2abe890de694922a16eb1398e16d4390cebce30f ([build#321](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=321)) should fix this for now.

I can't test it so please check if your problem is still reproducible using this fix.

**Comment by s3n-w6i** [comment]
Works like a charm, thanks!
