### ISSUE TITLE
Timetable empty, Rooms/Classes/Teachers all greyed-out

### ISSUE THREAD

**Issue by woffs** [SapuSeven/BetterUntis#449]
### Steps to Reproduce

Login to "Merian-Schule Berlin" (works both with key+"Passwort direkt benutzen" or with password without that option) via nessa.webuntis.com
Look into Timetable, Rooms, Teachers etc.

### Expected Result

Timetables to be shown, Filters/Rooms etc. clickable

### Actual Result

Timetable is empty ("Letzte Aktualisierung: nie") even after refresh

Teachers and rooms tabs are shown, but greyed out and not selectable

Logcat says:
```
09-11 08:29:39.082 18280 18280 D WeekView: Loading items for 2024-09-09
09-11 08:29:39.086 18280 18280 D TimetableLoaderDebug: target TimetableLoaderTarget(startDate=2024-09-09, endDate=2024-09-14, id=983, type=LEGAL_GUARDIAN) (requestId 7): cached file missing
09-11 08:29:39.091 18280 19251 I System.out: checkUrl: https://nessa.webuntis.com/WebUntis/jsonrpc_intern.do?school=Merian-Schule+Berlin&v=a5.2.3
09-11 08:29:39.092 18280 18296 I System.out: checkUrl: https://nessa.webuntis.com/WebUntis/jsonrpc_intern.do?school=Merian-Schule+Berlin&v=a5.2.3
09-11 08:29:39.093 18280 19251 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
09-11 08:29:39.096 18280 19251 I System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
09-11 08:29:39.097 18280 18296 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
09-11 08:29:39.103 18280 18296 I System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
09-11 08:29:39.456 18280 19251 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
09-11 08:29:39.457 18280 19251 I System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
09-11 08:29:39.460 18280 18296 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
09-11 08:29:39.461 18280 18296 I System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
09-11 08:29:39.563 18280 19251 I System.out: Check isMmsSendPdu
09-11 08:29:39.564 18280 19251 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
09-11 08:29:39.567 18280 18296 I System.out: Check isMmsSendPdu
09-11 08:29:39.567 18280 18296 W System  : ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
09-11 08:29:39.569 18280 18296 I System.out: [OkHttp] sendRequest<<
09-11 08:29:39.569 18280 19251 I System.out: [OkHttp] sendRequest<<
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: target TimetableLoaderTarget(startDate=2024-09-09, endDate=2024-09-14, id=983, type=LEGAL_GUARDIAN) (requestId 7): network request failed at Untis API level
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: s9.h: invalid element type: 12
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at s9.n.a(SourceFile:574)
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at s9.m.j(SourceFile:14)
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at za.a.k(SourceFile:9)
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at kotlinx.coroutines.i0.run(SourceFile:111)
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at androidx.compose.ui.platform.u0.i0(SourceFile:7)
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at androidx.compose.ui.platform.t0.run(SourceFile:3)
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at android.os.Handler.handleCallback(Handler.java:790)
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at android.os.Looper.loop(Looper.java:164)
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at android.app.ActivityThread.main(ActivityThread.java:6548)
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at java.lang.reflect.Method.invoke(Native Method)
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
09-11 08:29:39.682 18280 18280 D TimetableLoaderDebug: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
09-11 08:29:39.683 18280 18280 D WeekView: All items received for 2024-09-09
```

### Android Version

Android 8.1.0

### BetterUntis Version

4.1.0-beta01 (28334728)

### Installation Source

F-Droid

### Additional information

"OpenUntis" and "Stundenplan" are also failing (empty timetables). WebUntis via Browser works.

**Comment by nwo9** [comment]
I can confirm this behavior.
Same app version, same installation source, same bug.
Operating system: e.os 1.8.1
School: Bunsen Gymnasium Heidelberg

**Comment by SapuSeven** [comment]
Is this still the case in version 5.0.0 (beta)?

**Comment by woffs** [comment]
5.0.0 beta crashes immediately before I can enter anything (eOS 3.0.1-a14-20250608498955-community-FP3)

**Comment by woffs** [comment]
> 5.0.0 beta crashes immediately before I can enter anything (eOS 3.0.1-a14-20250608498955-community-FP3)

logcat says:

```
06-23 16:50:05.168  6234  6234 E AndroidRuntime: FATAL EXCEPTION: main
06-23 16:50:05.168  6234  6234 E AndroidRuntime: Process: com.sapuseven.untis, PID: 6234
06-23 16:50:05.168  6234  6234 E AndroidRuntime: java.lang.NullPointerException
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at com.sapuseven.untis.data.repository.UserSettingsRepository.getUserSettings(SourceFile:4)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at com.sapuseven.untis.data.repository.UserSettingsRepository.getUserSettings(SourceFile:1)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at I5.b.a(SourceFile:1614)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at O9.A.A(SourceFile:143)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at O9.A.a(SourceFile:1)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at Q1.t.y(SourceFile:104)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at c8.a.k(SourceFile:9)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at K9.N.run(SourceFile:115)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at J0.f0.r0(SourceFile:7)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at J0.e0.run(SourceFile:3)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8592)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
06-23 16:50:05.168  6234  6234 E AndroidRuntime: 	Suppressed: P9.e: [J0.K0@ae79987, X.f@acdb0b4, x0{Cancelling}@4a344dd, f0@86dd852]

```

**Comment by SapuSeven** [comment]
@woffs please make sure to use the latest **beta03**: https://github.com/SapuSeven/BetterUntis/releases/tag/5.0.0-beta03

**Comment by woffs** [comment]
ok, beta03 does not crash 👍 
but this issue is not fixed yet:

```
06-23 17:05:56.218  6538  6538 E TimetableViewModel: Failed to load timetable due to API error
06-23 17:05:56.218  6538  6538 E TimetableViewModel: P5.a: invalid element type: 12
06-23 17:05:56.218  6538  6538 E TimetableViewModel: 	at O5.u.d(SourceFile:161)
06-23 17:05:56.218  6538  6538 E TimetableViewModel: 	at O5.q.y(SourceFile:24)
06-23 17:05:56.218  6538  6538 E TimetableViewModel: 	at c8.a.k(SourceFile:9)
06-23 17:05:56.218  6538  6538 E TimetableViewModel: 	at K9.G0.r(SourceFile:27)
06-23 17:05:56.218  6538  6538 E TimetableViewModel: 	at K9.a.k(SourceFile:23)
06-23 17:05:56.218  6538  6538 E TimetableViewModel: 	at c8.a.k(SourceFile:32)
06-23 17:05:56.218  6538  6538 E TimetableViewModel: 	at K9.N.run(SourceFile:115)
06-23 17:05:56.218  6538  6538 E TimetableViewModel: 	at E1.a.b(SourceFile:6)
06-23 17:05:56.218  6538  6538 E TimetableViewModel: 	at E1.a.run(SourceFile:479)
06-23 17:05:56.218  6538  6538 E TimetableViewModel: 	at R9.j.run(SourceFile:3)
06-23 17:05:56.218  6538  6538 E TimetableViewModel: 	at R9.a.run(SourceFile:94)

```
