### ISSUE TITLE
[Feature Request] Wear Support

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#61]
**Describe the solution you'd like**
It would be nice if there was an option to see the current day on your watch.

**Comment by Domi04151309** [comment]
I am currently working on that feature.

**Comment by Domi04151309** [comment]
I am running into an issue with the communication between the watch and the phone. The watch only receives messages when it feels like it. This is absolutely random.

**Comment by SapuSeven** [comment]
Sorry to hear that.
Unfortunately I cannot help you as I don't own a smartwatch.

**Comment by Domi04151309** [comment]
I have kind of figured it out now.
Can you describe or show me code that gets the timetable data from Untis? That would speed up development a lot.

**Comment by SapuSeven** [comment]
### Construct a `TimetableLoader`

    val timetableLoader = TimetableLoader(WeakReference(context), timetableDisplay, profileUser, timetableDatabaseInterface)

- `context` is just the `Context` of an activity (not sure how it works in your case)
- `timetableDisplay` is any object extending `TimetableDisplay`, this contains the callback functions `addTimetableItems` and `onTimetableLoadingError`
- `profileUser` and `timetableDatabaseInterface`: load a profile from the user database like this:
```
val userDatabase = UserDatabase.createInstance(context)
userDatabase.getUser(profileId)?.let {
    profileUser = it
    timetableDatabaseInterface = TimetableDatabaseInterface(userDatabase, it.id ?: -1)
}
```

You need to specify a `profileId` or load the currently selected profile id like this:

    preferenceManager.currentProfileId()

`preferenceManager` is just a `PreferenceManager(context)` object.

---

### Specify a target timetable

    val target = TimetableLoader.TimetableLoaderTarget(...)

see https://github.com/SapuSeven/BetterUntis/blob/master/app/src/main/java/com/sapuseven/untis/helpers/timetable/TimetableLoader.kt#L160-L165

---

### Load the timetable

    timetableLoader.load(target, flags, proxyHost)

---

For `proxyHost`, use the `preferenceManager` from above:

    val proxyHost = preferenceManager.defaultPrefs.getString("preference_connectivity_proxy_host", null)

---

`flags` can be an OR-combination of `TimetableLoader.FLAG_LOAD_CACHE` `TimetableLoader.FLAG_LOAD_SERVER`.

I recommend you use only `FLAG_LOAD_CACHE` and check for error codes like this:

```
override fun onTimetableLoadingError(requestId: Int, code: Int?, message: String?) {
	when (code) {
		TimetableLoader.CODE_CACHE_MISSING -> timetableLoader.repeat(requestId, TimetableLoader.FLAG_LOAD_SERVER, proxyHost)
		else -> {
			// show error message
		}
	}
}
```
That way cache is used if available and only loads from the server if necessary.

---

Let's hope I didn't forget anything :)

**Comment by Domi04151309** [comment]
Thanks @SapuSeven that's already a lot of information.
What do you think is the best method for copying a profile to the watch? I'd suggest to only copy the currently selected profile to the watch.
It would be nice to copy as less as possible like only the username, school and password.

**Comment by SapuSeven** [comment]
I really don't know how smartwatch development works.
Fact is that the app uses more than just authentication details to display the timetable, as the API provides IDs for every element instead of plain text names.
So to view the timetable, you'd need at least data from every table in the `userdata.db` database with the `_user_id` field corresponding to the current profile.

**Comment by Domi04151309** [comment]
It basically works the same way as with phone development. I am currently trying to copy over the logic from the LoginDataInputActivity so that I can create a user on the watch.

**Comment by Domi04151309** [comment]
Some stuff will likely be duplicated so it is worth considering to export the basic logic to a module and only leave the data adaption in the app modules.

**Comment by Domi04151309** [comment]
I am having issues with getting the timetable. Can you help me print the lessons for the current day to the logs?

[Code](https://github.com/Domi04151309/BetterUntis/blob/3d5ed623b3343a88ee22630df0a1870fbd4581b4/wear/src/main/java/com/sapuseven/untis/wear/activities/MainActivity.kt#L56)

Most of the classes are just copied over but i have to use a modified TimetableLoader and TimetableGridItem because i don't use the weekview.

**Comment by SapuSeven** [comment]
Alright, first of all we should definitely avoid these duplicate files in the project later on.

Anyways, here's what I would do in the mentioned code section to quickly test it:
```
        val today = UntisDate.fromLocalDate(LocalDate.now())

        timetableLoader.load(TimetableLoader.TimetableLoaderTarget(today, today, profileUser.userData.elemId, profileUser.userData.elemType ?: ""), TimetableLoader.FLAG_LOAD_SERVER)
```

and set a breakpoint inside the `addTimetableItems` function to inspect the `items` parameter of said function.

**Comment by Domi04151309** [comment]
With the code above the app crashes with the following error
```
2020-03-18 15:55:36.344 25526-25526/com.sapuseven.untis.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sapuseven.untis.debug, PID: 25526
    kotlinx.serialization.json.JsonUnknownKeyException: Strict JSON encountered unknown key: jsonrpc
    You can disable strict mode to skip unknown keys
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeElementIndex(StreamingJsonInput.kt:96)
        at com.sapuseven.untis.models.untis.response.TimetableResponse$$serializer.deserialize(Unknown Source:18)
        at com.sapuseven.untis.models.untis.response.TimetableResponse$$serializer.deserialize(TimetableResponse.kt:8)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
        at kotlinx.serialization.CoreKt.decode(Core.kt:79)
        at kotlinx.serialization.json.Json.parse(Json.kt:148)
        at com.sapuseven.untis.wear.helpers.TimetableLoader.loadFromServer(TimetableLoader.kt:102)
        at com.sapuseven.untis.wear.helpers.TimetableLoader$loadFromServer$1.invokeSuspend(Unknown Source:13)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

This is really strange because as far as I understand the code [strict mode is already disabled](https://github.com/Domi04151309/BetterUntis/blob/76977610c9819c0b78859ba6cb166ef4e18b904e/wear/src/main/java/com/sapuseven/untis/helpers/SerializationUtils.kt#L9) and the key [`jsonrpc` is known](https://github.com/Domi04151309/BetterUntis/blob/76977610c9819c0b78859ba6cb166ef4e18b904e/wear/src/main/java/com/sapuseven/untis/models/untis/response/BaseResponse.kt#L10).

**Comment by SapuSeven** [comment]
Look at #14 , it's a weird bug, just clean the project before you build it.

**Comment by Domi04151309** [comment]
## Quick Status Update

### Screenshots
| Setup | Connecting | Timetable | Timetable 2 |
| - | - | - | - |
| ![1](https://user-images.githubusercontent.com/36272047/76994834-4178f380-694f-11ea-8f1e-8d8d889a3842.png) | ![2](https://user-images.githubusercontent.com/36272047/76994852-48076b00-694f-11ea-962c-3e637db29047.png) | ![3](https://user-images.githubusercontent.com/36272047/76994887-53f32d00-694f-11ea-9865-a929efc3ca75.png) | ![4](https://user-images.githubusercontent.com/36272047/76994919-5d7c9500-694f-11ea-849c-81d93c7db4d1.png) |

### Status:
- [X] Logging in
- [X] Viewing timetable
- [X] Rotary input
- [X] Reloading
- [X] Logging out
- [x] Merging multihour lessons
- [x] Visual feedback on phone when profile is copied over
- [x] Caching
- [x] Error handling
- [x] Logging in with correct profile / key

**Comment by SapuSeven** [comment]
That already looks really nice!
As I mentioned, there's still some work to do to avoid duplicate code between the main and the smartwatch code.

**Comment by Domi04151309** [comment]
I would recommend merging the `wear-support` branch when I have implemented everything and then creating a new branch and copying over the logic to a new module which can be included in the `app` and the `wear` module.

**Comment by SapuSeven** [comment]
That sounds like a great idea.

I think you don't need to worry about merging multihour lessons as this will be implemented in that shared module.

I'll start working on it after your PR.

**Comment by Domi04151309** [comment]
I think i have found quite an effective method for merging multihour lessons.
I first sort the array by the time the lesson starts and then cycle through the array and check if there is an item with the same name and a start time that matches the end time.

**Comment by SapuSeven** [comment]
Only problem with that is if you have something like a 5 minute break between the lessons. Start and end time won't match in that case.

That's why I went with sorting the items into a timegrid.

**Comment by Domi04151309** [comment]
I think we can have two methods for that. One optimized for a list and one optimized for the weekview.

**Comment by Domi04151309** [comment]
Some planning

#### Modules:
- app
- wear
- weekview
- untis

#### `app`
All things related directly to the app, e.g.:
- com.sapuseven.untis.activities.*
- com.sapuseven.untis.adapters.*
- com.sapuseven.untis.dialogs.*
- com.sapuseven.untis.preferences.*
- com.sapuseven.untis.receivers.*
- com.sapuseven.untis.views.*
- com.sapuseven.untis.widget.*

#### `wear`
All things related to the wear app, e.g.:
- com.sapuseven.untis.wear.*

#### `weekview`
No changes there

#### `untis`
All things related to the "deeper workings" of the app, e.g.:
- com.sapuseven.untis.annotations.*
- com.sapuseven.untis.data.*
- com.sapuseven.untis.helpers.*
- com.sapuseven.untis.interfaces.*
- com.sapuseven.untis.models.*

**Comment by SapuSeven** [comment]
That looks great to me.
How do you plan on integrating these changes? You can submit pull requests for a new branch if you like.

**Comment by Domi04151309** [comment]
I plan to wait until you finished the teacher specific features to not cause unnecessary extra work.

**Comment by H4K0N42** [comment]
Will the Galaxy store for the Samsung Watches supported too?

**Comment by SapuSeven** [comment]
I'm sorry but currently there are no plans to support any other platform than Wear OS.
Even then it will probably be a while until smart watches are supported, as this PR is quite out of date by now and I'm not actively working on it myself.

**Comment by thetechnikfreak** [comment]
@SapuSeven I try it out using Side loading the app technically works on Wear os just the UI is way to larger I don't know if that's an easy thing to do but if would it be possible for you to just adjust the UI size so we can use it on wear os

**Comment by SapuSeven** [comment]
There has been a lot of development in the WearOS world since this issue was raised.
At this point it would make sense to have a dedicated user interface for wearables since the app architecture has been updated a lot as well.
I do own a Pixel Watch 2 so I can do some real-world testing, but I've not started any development for it.
Getting version 5 to a stable release is the priority right now, but I would definitely like to include this in the future.

**Comment by EmilEmilchen** [comment]
Just found this Feature Request after having started to implement some kind of WearOS - Untis Frontend myself, I have been looking for this exact feature in ANY Untis Frontend for a few months.

@SapuSeven Do you think it'd be worthwhile for me to try and get the ~5 year old implementation from above (#70) working?

I don't even even know what an approximate ETA for the above mentioned v5 stable release would be, not to mention a proper WearOS app... Just curious.

Edit: Well, I only just discovered that the API used in v3 of this app has apparently been deprecated by Untis so I guess it'd be more work than I had expected to get this running again...

**Comment by SapuSeven** [comment]
I would definitely say start from scratch.
A v5 stable release will likely still take a while, I'm working on modularizing the application which requires a lot of clean-up.
But the good news: I'm keeping WearOS compatibility in mind, so once the changes are complete it will be really easy to get the data from Untis and display it in an independent WearOS module.

**Comment by EmilEmilchen** [comment]
Okay, thanks for the info as well as the swift response. I guess I'll at least wait for the v5 stable release then.

An ugly workaround for the meantime I've found is to install the normal app on the watch.
