### ISSUE TITLE
Crash when logging in

### ISSUE THREAD

**Issue by Jan200101** [SapuSeven/BetterUntis#7]
After reinstalling BetterUntis, this time downloaded from sapuseven.com/app/BetterUntis/ instead of build myself, it manages to crash every time when logging it.
The Demo school worked just fine for me

logcat
> 10-06 21:06:51.449  8328  8328 E AndroidRuntime: Process: com.sapuseven.untis.debug, PID: 8328
> 10-06 21:06:51.449  8328  8328 E AndroidRuntime: 	at com.sapuseven.untis.models.UntisUserData$$serializer.deserialize(Unknown Source:149)
> 10-06 21:06:51.449  8328  8328 E AndroidRuntime: 	at com.sapuseven.untis.models.UntisUserData$$serializer.deserialize(UntisUserData.kt:10)
> 10-06 21:06:51.449  8328  8328 E AndroidRuntime: 	at com.sapuseven.untis.models.untis.response.UserDataResponse$$serializer.deserialize(Unknown Source:142)
> 10-06 21:06:51.449  8328  8328 E AndroidRuntime: 	at com.sapuseven.untis.models.untis.response.UserDataResponse$$serializer.deserialize(UserDataResponse.kt:7)
> 10-06 21:06:51.449  8328  8328 E AndroidRuntime: 	at com.sapuseven.untis.activities.LoginDataInputActivity.acquireUserData(LoginDataInputActivity.kt:275)
> 10-06 21:06:51.449  8328  8328 E AndroidRuntime: 	at com.sapuseven.untis.activities.LoginDataInputActivity$acquireUserData$1.invokeSuspend(Unknown Source:13)
> 10-06 21:06:51.457  1447  1907 W ActivityManager:   Force finishing activity com.sapuseven.untis.debug/com.sapuseven.untis.activities.LoginDataInputActivity

**Comment by SapuSeven** [comment]
I suspect that the Untis API sends new JSON keys with your school. Does the app crash even with anonymous user? If yes, could you send me the school ID?
Otherwise you'd have to figure out what key is missing by debugging yourself.

**Comment by SapuSeven** [comment]
Just some more technical details: BetterUntis uses Kotlin Serialization to deserialize JSON. Debug builds use strict mode by default, so any key in the JSON data that is not in the implementing class will cause a crash.

**Comment by Jan200101** [comment]
anonymous users work fine
my school id is BK-Ostvest

**Comment by SapuSeven** [comment]
Thank you. I suggest you use the anonymous login with a custom personal timetable while I try to locate the issue.
Alternatively, you could compile the app yourself using the release variant to bypass strict mode.

**Comment by Jan200101** [comment]
Same result when building the release apk

> 
> 10-06 21:50:45.727 13997 13997 E AndroidRuntime: Process: com.sapuseven.untis, PID: 13997
> 10-06 21:50:45.727 13997 13997 E AndroidRuntime: 	at com.sapuseven.untis.models.UntisUserData$$serializer.deserialize(Unknown Source:136)
> 10-06 21:50:45.727 13997 13997 E AndroidRuntime: 	at com.sapuseven.untis.models.UntisUserData$$serializer.deserialize(Unknown Source:0)
> 10-06 21:50:45.727 13997 13997 E AndroidRuntime: 	at com.sapuseven.untis.models.untis.response.UserDataResponse$$serializer.deserialize(Unknown Source:127)
> 10-06 21:50:45.727 13997 13997 E AndroidRuntime: 	at com.sapuseven.untis.models.untis.response.UserDataResponse$$serializer.deserialize(Unknown Source:0)
> 10-06 21:50:45.727 13997 13997 E AndroidRuntime: 	at com.sapuseven.untis.activities.LoginDataInputActivity.b(:17)
> 10-06 21:50:45.733  1447  1476 W ActivityManager:   Force finishing activity com.sapuseven.untis/.activities.LoginDataInputActivity
>

**Comment by SapuSeven** [comment]
Ouch

Do you have the full stacktrace with the error message?

**Comment by Jan200101** [comment]
this is sadly all I could find with logcat

**Comment by SapuSeven** [comment]
I just added a primitive crash log dialog which shows the full stack trace when you start the app after a crash.
Could you use the latest build to provide this log?

**Comment by Jan200101** [comment]
```
kotlinx.serialization.SerializationException: Can't locate argument-less serializer for class kotlin.Any. For generic classes, such as lists, please provide serializer explicitly.
	at kotlinx.serialization.PlatformUtilsKt.serializer(PlatformUtils.kt:28)
	at kotlinx.serialization.modules.SerialModuleExtensionsKt.getContextualOrDefault(SerialModuleExtensions.kt:27)
	at kotlinx.serialization.ContextSerializer.deserialize(ContextSerializer.kt:36)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Coders.kt:116)
	at kotlinx.serialization.json.JsonInput$DefaultImpls.decodeNullableSerializableValue(Unknown Source:8)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeNullableSerializableValue(StreamingJsonInput.kt:11)
	at kotlinx.serialization.ElementValueDecoder.decodeNullableSerializableElement(ElementWise.kt:144)
	at com.sapuseven.untis.models.UntisUserData$$serializer.deserialize(Unknown Source:149)
	at com.sapuseven.untis.models.UntisUserData$$serializer.deserialize(UntisUserData.kt:10)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Coders.kt:116)
	at kotlinx.serialization.json.JsonInput$DefaultImpls.decodeNullableSerializableValue(Unknown Source:8)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeNullableSerializableValue(StreamingJsonInput.kt:11)
	at kotlinx.serialization.ElementValueDecoder.decodeNullableSerializableElement(ElementWise.kt:144)
	at com.sapuseven.untis.models.untis.response.UserDataResponse$$serializer.deserialize(Unknown Source:142)
	at com.sapuseven.untis.models.untis.response.UserDataResponse$$serializer.deserialize(UserDataResponse.kt:7)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.CoreKt.decode(Core.kt:79)
	at kotlinx.serialization.json.Json.parse(Json.kt:148)
	at com.sapuseven.untis.activities.LoginDataInputActivity.acquireUserData(LoginDataInputActivity.kt:275)
	at com.sapuseven.untis.activities.LoginDataInputActivity$acquireUserData$1.invokeSuspend(Unknown Source:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:208)
	at android.app.ActivityThread.main(Unknown Source:107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)

```

**Comment by SapuSeven** [comment]
Thanks, I'll look into that.

**Comment by SapuSeven** [comment]
I added logging for unknown elements in the latest build. Could you try to login again and search the LogCat for warning messages with tag `UnknownObject`? It also shouldn't crash any more.

**Comment by Jan200101** [comment]
With the new app I can log in without issue

There was only one instance of UnknownObject in the logcat output
```
10-08 09:31:42.705 19694 19694 W UnknownObject: Unknown JSON object messengerSettings encountered: {"serverUrl":"6618300.grape.webuntis.com","organizationId":"710"}```

**Comment by SapuSeven** [comment]
Great!
Thank you for the log, it was really useful.
