### ISSUE TITLE
[Project] Rebuilding The Backend

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#87]
This issue is for generating a detailed API documentation to be able to build an open source backend.

**Comment by Domi04151309** [comment]
If I see this correctly all the different API objects are in [`com.sapuseven.untis.models`](https://github.com/SapuSeven/BetterUntis/tree/master/app/src/main/java/com/sapuseven/untis/models).

**Comment by SapuSeven** [comment]
Basically, yeah. All classes starting with `Untis` in this package are the objects you usually work with when processing the API data and the subpackage `untis` contains additional models required for communicating with the API.

**Comment by Domi04151309** [comment]
The current testing API crashes with the following message when trying to login.

```
kotlinx.serialization.json.JsonParsingException: Invalid JSON at 75: Expected '{, kind: kotlinx.serialization.StructureKind$CLASS@10615c6'
	at kotlinx.serialization.json.internal.StreamingJsonInput.beginStructure(StreamingJsonInput.kt:116)
	at com.sapuseven.untis.models.untis.UntisErrorData$$serializer.deserialize(Unknown Source:10)
	at com.sapuseven.untis.models.untis.UntisErrorData$$serializer.deserialize(UntisError.kt:13)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Coders.kt:116)
	at kotlinx.serialization.json.JsonInput$DefaultImpls.decodeNullableSerializableValue(Unknown Source:8)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeNullableSerializableValue(StreamingJsonInput.kt:11)
	at kotlinx.serialization.ElementValueDecoder.decodeNullableSerializableElement(ElementWise.kt:144)
	at com.sapuseven.untis.models.untis.UntisError$$serializer.deserialize(Unknown Source:97)
	at com.sapuseven.untis.models.untis.UntisError$$serializer.deserialize(UntisError.kt:6)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Coders.kt:116)
	at kotlinx.serialization.json.JsonInput$DefaultImpls.decodeNullableSerializableValue(Unknown Source:8)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeNullableSerializableValue(StreamingJsonInput.kt:11)
	at kotlinx.serialization.ElementValueDecoder.decodeNullableSerializableElement(ElementWise.kt:144)
	at com.sapuseven.untis.models.untis.response.UserDataResponse$$serializer.deserialize(Unknown Source:96)
	at com.sapuseven.untis.models.untis.response.UserDataResponse$$serializer.deserialize(UserDataResponse.kt:10)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.CoreKt.decode(Core.kt:79)
	at kotlinx.serialization.json.Json.parse(Json.kt:148)
	at com.sapuseven.untis.activities.LoginDataInputActivity.acquireUserData(LoginDataInputActivity.kt:304)
	at com.sapuseven.untis.activities.LoginDataInputActivity$acquireUserData$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by SapuSeven** [comment]
I _think_ this can be resolved by changing the type of `data` to `UnknownObject?` in [UntisError.kt](https://github.com/SapuSeven/BetterUntis/blob/0f3e605f3a778a7ad8abab7d1c7f533d0198544e/app/src/main/java/com/sapuseven/untis/models/untis/UntisError.kt#L9). I haven't quite figured out how to return errors the way the Untis API does.
